version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12-stretch
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install application dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths:
            - repo

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Create test configuration file
          command: |
            cp conf/config.json.template conf/config.json
            sed -i "s/GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/i" conf/config.json
            sed -i "s/API_USER//i" conf/config.json
            sed -i "s/API_PASSWORD//i" conf/config.json

      - run:
          name: Start API server
          command: npm run server
          background: true

      - run:
          name: Wait for test server to be running
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:$PORT
            :

      - run:
          name: Run API tests
          command: npm run apiTest

      - run:
          name: Check code style
          command: npm run lint

  deploy:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

      - run:
          name: Setup git user
          command: |
            git config user.email "jakub.niezgoda@nitarch.pl"
            git config user.name "qooban"

      - run:
          name: Update main branch
          command: |
            git checkout ${MAIN_BRANCH}
            git merge --ff-only ${CIRCLE_BRANCH}
            git push -q https://${GITHUB_TOKEN}@github.com/edk-software/edk-route-verifier.git ${MAIN_BRANCH}

      - run:
          name: Remove publish branch
          command: |
            git push -q https://${GITHUB_TOKEN}@github.com/edk-software/edk-route-verifier.git --delete ${CIRCLE_BRANCH}

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: /^publish-v.*/
